### ISSUE TITLE
[bug]UnboundLocalError，这个错误表示在代码中试图访问一个本地变量，但该变量在使用之前并没有被赋值

### ISSUE THREAD

**Issue by liuhuabaobao** [zhongwen-4/nonebot-plugin-text-ban#2]
在 nonebot_plugin_text_ban 插件的 is_msg_handle 函数中（文件路径\nonebot_plugin_text_ban\__init__.py，行号为 140），代码尝试通过 [a["text"] for a in text["texts"] if "text" in a] 这样的列表推导式来获取 text 变量中 texts 列表里每个元素的 text 字段值，但此时 text 变量并没有被赋值，所以导致了这个错误

**Comment by zhongwen-4** [comment]
已修复
