### ISSUE TITLE
【bug反馈】无法查看违禁词列表

### ISSUE THREAD

**Issue by liuhuabaobao** [zhongwen-4/nonebot-plugin-text-ban#4]
![IMG_20241224_063925](https://github.com/user-attachments/assets/99498bad-397c-469f-a0b9-ef6dce56f175)
![IMG_20241224_063903](https://github.com/user-attachments/assets/d8295139-323c-4234-908d-ea60a2eb5012)

**Comment by zhongwen-4** [comment]
怎么触发的bug，事先配置了违禁词吗，协议端的名称和版本呢？

**Comment by liuhuabaobao** [comment]
配置了违禁词的，用的是llonebot（）

**Comment by zhongwen-4** [comment]
> 配置了违禁词的，用的是llonebot（）

如何复现

**Comment by liuhuabaobao** [comment]
当时是发送 list 就能复现，但是我现在换拉格朗了，无法复现（）

**Comment by zhongwen-4** [comment]
![image](https://github.com/user-attachments/assets/6aa34cc4-94d7-4a81-a135-a1d78ae334f4)
